# Generated by Django 3.2.18 on 2023-02-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='identification_number',
            field=models.CharField(default='12312313123', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
