# Generated by Django 3.2.18 on 2023-02-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transfer_processing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='sender_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='taker_account',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='app.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='app.account'),
            preserve_default=False,
        ),
    ]
