# Generated by Django 3.2.18 on 2023-02-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
