# Generated by Django 3.2.18 on 2023-02-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
